framework:
    messenger:
        failure_transport: failed

        transports:
            inbox:
                serializer: app.serializer.messenger.external_json_serializer
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: inbox
                        type: direct
                        default_publish_routing_key: inbox
                    queues:
                        messages:
                            binding_keys: [ inbox ]

            failed:
                dsn: "%env(MESSENGER_TRANSPORT_DSN_FAILED)%"

        buses:
            app.command_bus: ~
            app.event_bus:
                default_middleware: allow_no_handlers

        default_bus: app.command_bus

        routing:
            'App\Messenger\Contract\MessageInterface': inbox
