framework:
    messenger:
        failure_transport: failed

        transports:
            failed:
                dsn: "%env(MESSENGER_TRANSPORT_DSN_FAILED)%"

            subscribe:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: amq.direct
                        type: direct
                        default_publish_routing_key: direct
                    queues:
                        user_management:
                            binding_keys: [create_user]

            publish:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: amq.direct
                        type: direct
                        default_publish_routing_key: direct

        default_bus: command_bus
        buses:
            command_bus:
                default_middleware: allow_no_handlers
                middleware:
                    - App\Messenger\Middleware\AuditMiddleware
            event_bus:
                default_middleware: allow_no_handlers
                middleware:
                    - App\Messenger\Middleware\AuditMiddleware

        routing:
            'App\Messenger\Contract\SubscribeMessageInterface': subscribe
            'App\Messenger\Contract\PublishMessageInterface': publish
