parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $messengerAuditLogger: '@monolog.logger.messenger_audit'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Messenger
    _instanceof:
        App\Handler\Contract\HandlerInterface:
            tags: ['app.handler']

    App\Messenger\External\ExternalMessageHandler:
        arguments:
            - !tagged_iterator app.handler



